DROP TABLE IF EXISTS pet;

CREATE TABLE pet(
	id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	category_id INTEGER,
	name VARCHAR(255),
	status enum("available", "pending", "sold")
);

DROP TABLE IF EXISTS category;

CREATE TABLE category(
	id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(255)
);

DROP TABLE IF EXISTS photo;

CREATE TABLE photo(
	id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	pet_id INTEGER,
	url VARCHAR(255)
);

DROP TABLE IF EXISTS tag;

CREATE TABLE tag(
	id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(255)
);

DROP TABLE IF EXISTS pet_tag;

CREATE TABLE pet_tag(
	pet_id INTEGER,
	tag_id INTEGER
);